server:
    port: 8082
    servlet:
      session:
        cookie:
          name: UISESSION
      context-path: /ui
security:
  oauth2:
    client:
      clientId: html5
      clientSecret: password
      accessTokenUri: http://localhost:9191/uaa/oauth/token
      userAuthorizationUri: http://localhost:9191/uaa/oauth/authorize
    resource:
      userInfoUri: http://localhost:9191/uaa/user
spring:
  thymeleaf:
    cache: false   