version: '3'

services:

  redis:
    image: redis:alpine
    networks:
      marketing-cloud:

  oracle-marketing:
    build:
      context: ./oracle
      dockerfile: Dockerfile
    image: marketingservice/oracle-xe:marketing
    networks:
      marketing-cloud:
      
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    image: marketingservice/config-service:latest
    ports:
    - 8888:8888
    networks:
      marketing-cloud:
    environment:
      SPRING_PROFILES_ACTIVE: stage    
     
  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    image: marketingservice/service-discovery:latest
    ports:
    - 8761:8761
    networks:
      marketing-cloud:
    depends_on:
    - config-service
    environment:
      SPRING_PROFILES_ACTIVE: stage
      CONFIG_SERVICE_URI: config-service
      CONFIG_SERVICE_PORT: 8888

  authorization-service:
    build:
      context: ./authorization-service
      dockerfile: Dockerfile
    image: marketingservice/authorization-service:latest
    ports:
    - 9191:9191
    networks:
      marketing-cloud:
    depends_on:
    - service-discovery
    - redis
    - oracle-marketing
    environment:
    
      SPRING_PROFILES_ACTIVE: stage
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ORACLE_HOST: oracle-marketing
      ORACLE_PORT: 1521
      ORACLE_SID: XE
      ORACLE_USER: marketing
      ORACLE_PASSWORD: marketing
      DISCOVERY_SERVICE_HOST: service-discovery
      DISCOVERY_SERVICE_PORT: 8761
      CONFIG_SERVICE_HOST: config-service
      CONFIG_SERVICE_PORT: 8888
      
  greetings-service:
    build:
      context: ./greetings-service
      dockerfile: Dockerfile
    image: marketingservice/greetings-service:latest
    networks:
      marketing-cloud:
    depends_on:
    - service-discovery
    - redis
    - config-service
    environment:
    
      SPRING_PROFILES_ACTIVE: stage
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DISCOVERY_SERVICE_HOST: service-discovery
      DISCOVERY_SERVICE_PORT: 8761
      CONFIG_SERVICE_HOST: config-service
      CONFIG_SERVICE_PORT: 8888
      
  marketing-gateway:
    build:
      context: ./marketing-gateway
      dockerfile: Dockerfile
    image: marketingservice/marketing-gateway:latest
    ports:
    - 8081:8081
    networks:
      marketing-cloud:
    depends_on:
    - service-discovery
    - config-service
    environment:
    
      SPRING_PROFILES_ACTIVE: stage
      DISCOVERY_SERVICE_HOST: service-discovery
      DISCOVERY_SERVICE_PORT: 8761
      CONFIG_SERVICE_HOST: config-service
      CONFIG_SERVICE_PORT: 8888
      
  marketing-ui:
    build:
      context: ./marketing-ui
      dockerfile: Dockerfile
    image: marketingservice/marketing-ui:latest
    ports:
    - 8082:8082
    networks:
      marketing-cloud:
    depends_on:
    - service-discovery
    - config-service
    environment:
    
      SPRING_PROFILES_ACTIVE: stage
      AUTH_SERVICE_HOST: localhost
      AUTH_SERVICE_PORT: 9191 
      DISCOVERY_SERVICE_HOST: service-discovery
      DISCOVERY_SERVICE_PORT: 8761
      CONFIG_SERVICE_HOST: config-service
      CONFIG_SERVICE_PORT: 8888
      
  marketing-service:
    build:
      context: ./marketing-service
      dockerfile: Dockerfile
    image: marketingservice/marketing-service:latest
    networks:
      marketing-cloud:
    depends_on:
    - service-discovery
    - config-service
    - oracle-marketing
    environment:
    
      SPRING_PROFILES_ACTIVE: stage
      AUTH_SERVICE_HOST: localhost
      AUTH_SERVICE_PORT: 9191 
      DISCOVERY_SERVICE_HOST: service-discovery
      DISCOVERY_SERVICE_PORT: 8761
      CONFIG_SERVICE_HOST: config-service
      CONFIG_SERVICE_PORT: 8888
      ORACLE_HOST: oracle-marketing
      ORACLE_PORT: 1521
      ORACLE_SID: XE
      ORACLE_USER: marketing
      ORACLE_PASSWORD: marketing
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      
  
networks:
  marketing-cloud: