server:
  port: 9191
  servlet:
    context-path: /uaa
---
spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
logging:
    level:
      org:
        springframework:
          security: DEBUG     
---
spring:
  profiles: dev-postgresql
  datasource:
    initialization-mode: never
    url: jdbc:postgresql://localhost:5432/AUTHORIZATION
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
---
spring:
  profiles: stage
  datasource:
    initialization-mode: never
    url: jdbc:oracle:thin:@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SID}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update 
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}