server:
  port: 9191
  servlet:
    context-path: /uaa
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: never
  liquibase:
    enabled: true
    contexts: test,ddl
    change-log: classpath:db/changelog/changelog-master.xml
  redis:
    host: localhost
    port: 6379
---
spring:
  profiles: dev
  jpa:
    show-sql: true
logging:
    level:
      org:
        springframework:
          security: DEBUG
---
spring:
  profiles: dev-postgresql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: never
    url: jdbc:postgresql://localhost:5432/AUTHORIZATION
    username: postgres
    password: postgres  
  liquibase:
    enabled: true
    contexts: ddl
    change-log: classpath:db/changelog/changelog-master.xml
---
spring:
  profiles: dev-h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: never
  liquibase:
    enabled: true
    contexts: ddl
    change-log: classpath:db/changelog/changelog-master.xml
---
spring:
  profiles: stage
  datasource:
    initialization-mode: never
    url: jdbc:oracle:thin:@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SID}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update 
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}