INSERT INTO SCOPES(ID,SCOPE_NAME,DESCRIPTION) VALUES(1,'openid','sample scope');

INSERT INTO CLIENTS(ID, AUTHORITIES, GRANT_TYPES, AUTHO_APPROVE_SCOPES, CLIENT_ID, SECRET) VALUES (1,null , 'authorization_code,refresh_token,password', '.*', 'html5', '$2a$10$0A38bBC1mlvVRYlHqODuD.kRg2urDdGdX4dIxDRPhDspg7l2zmzUu');
INSERT INTO CLIENTS(ID, AUTHORITIES, GRANT_TYPES, AUTHO_APPROVE_SCOPES, CLIENT_ID, SECRET) VALUES (2,null , 'authorization_code,refresh_token,password', '.*', 'android', 'secret');

INSERT INTO CLIENTS_SCOPES(CLIENT_ID,SCOPE_ID) VALUES(1,1);
INSERT INTO CLIENTS_SCOPES(CLIENT_ID,SCOPE_ID) VALUES(2,1);