INSERT INTO CLIENTS(ID, REGISTER_DATE, UPDATE_DATE, CLIENT_NAME, SECRET) VALUES (50,null,null,'client1','secret1');
INSERT INTO CLIENTS(ID, REGISTER_DATE, UPDATE_DATE, CLIENT_NAME, SECRET) VALUES (51,null,null,'client2','secret2');


INSERT INTO AUTHORITIES(ID, REGISTER_DATE, UPDATE_DATE, AUTHORITY_NAME, DESCRIPTION) VALUES (50,null,null,'ROLE_ADMIN','Admin Authority');
INSERT INTO AUTHORITIES(ID, REGISTER_DATE, UPDATE_DATE, AUTHORITY_NAME, DESCRIPTION) VALUES (51,null,null,'ROLE_CLIENT','Client Authority');

INSERT INTO AUTHORITIES_CLIENTS(AUTHORITY_ID, CLIENT_ID) VALUES (50,50);
INSERT INTO AUTHORITIES_CLIENTS(AUTHORITY_ID, CLIENT_ID) VALUES (51,51);

INSERT INTO CLIENT_GRANT_TYPES(ID,REGISTER_DATE, UPDATE_DATE, TYPE_NAME,CLIENT_ID) VALUES (50,null,null,'AUTHORIZATION_CODE',50);
INSERT INTO CLIENT_GRANT_TYPES(ID,REGISTER_DATE, UPDATE_DATE, TYPE_NAME,CLIENT_ID) VALUES (51,null,null,'REFRESH_TOKEN',50);
INSERT INTO CLIENT_GRANT_TYPES(ID,REGISTER_DATE, UPDATE_DATE, TYPE_NAME,CLIENT_ID) VALUES (52,null,null,'PASSWORD',50);

INSERT INTO CLIENT_GRANT_TYPES(ID,REGISTER_DATE, UPDATE_DATE, TYPE_NAME,CLIENT_ID) VALUES (53,null,null,'AUTHORIZATION_CODE',51);
INSERT INTO CLIENT_GRANT_TYPES(ID,REGISTER_DATE, UPDATE_DATE, TYPE_NAME,CLIENT_ID) VALUES (54,null,null,'REFRESH_TOKEN',51);
