INSERT INTO ROLES(ID, REGISTER_DATE, UPDATE_DATE, ROLE_NAME, DESCRIPTION) VALUES (50,null,null,'ROLE_ADMIN','blah blah');
INSERT INTO ROLES(ID, REGISTER_DATE, UPDATE_DATE, ROLE_NAME, DESCRIPTION) VALUES (51,null,null,'ROLE_USER','blah blah');

INSERT INTO GROUPS(ID, REGISTER_DATE, UPDATE_DATE, GROUP_NAME, DESCRIPTION) VALUES (50,null,null,'group1','blah blah');
INSERT INTO GROUPS(ID, REGISTER_DATE, UPDATE_DATE, GROUP_NAME, DESCRIPTION) VALUES (51,null,null,'group2','blah blah');


INSERT INTO ROLES_GROUPS(ROLE_ID,GROUP_ID) VALUES (50,50);
INSERT INTO ROLES_GROUPS(ROLE_ID,GROUP_ID) VALUES (51,50);

INSERT INTO ROLES_GROUPS(ROLE_ID,GROUP_ID) VALUES (51,51);

INSERT INTO USERS(ID, REGISTER_DATE,UPDATE_DATE,USER_NAME,PASS_WORD,EMAIL,MOBILE_NUMBER,FIRST_NAME,LAST_NAME,EXP_DATE,CRE_EXP_DATE,ENABLED,LOCKED)
VALUES(50,null,null,'koorosh01','123456789','kasraei.ar@gmail.com','00989123853840','alireza','kasraei',null,null,1,0);

INSERT INTO USERS_GROUPS(USER_ID,GROUP_ID) VALUES (50,50);