INSERT INTO VALUE_TYPES(ID,TYPE_NAME) VALUES (1,'روز');
INSERT INTO VALUE_TYPES(ID,TYPE_NAME) VALUES (2,'ماه');
INSERT INTO VALUE_TYPES(ID,TYPE_NAME) VALUES (3,'سال');
--
INSERT INTO ASSIGNED_STATUS_TYPES(ID,TYPE_NAME,TYPE_CODE) VALUES (1,'تخصیص یافته به شعبه','AST1');
INSERT INTO ASSIGNED_STATUS_TYPES(ID,TYPE_NAME,TYPE_CODE) VALUES (2,'افتتاح حساب','AST2');
INSERT INTO ASSIGNED_STATUS_TYPES(ID,TYPE_NAME,TYPE_CODE) VALUES (3,'در انتظار کمیته وام','AST3');
INSERT INTO ASSIGNED_STATUS_TYPES(ID,TYPE_NAME,TYPE_CODE) VALUES (4,'صدور دسته چک','AST4');
--
INSERT INTO ATTRACTION_TYPES(ID,TYPE_NAME,TYPE_CODE) VALUES (1,'بالقوه','AT1');
INSERT INTO ATTRACTION_TYPES(ID,TYPE_NAME,TYPE_CODE) VALUES (2,'راغب','AT2');
INSERT INTO ATTRACTION_TYPES(ID,TYPE_NAME,TYPE_CODE) VALUES (3,'در حال جذب','AT3');
--
INSERT INTO BUSINESS_SCALES(ID,BUSINESS_SCALE_NAME) VALUES (1,'شرکت بزرگ');
INSERT INTO BUSINESS_SCALES(ID,BUSINESS_SCALE_NAME) VALUES (2,'شرکت متوسط و کوچک');
INSERT INTO BUSINESS_SCALES(ID,BUSINESS_SCALE_NAME) VALUES (3,'موسسه غیردولتی');
INSERT INTO BUSINESS_SCALES(ID,BUSINESS_SCALE_NAME) VALUES (4,'نهاد دولتی');
INSERT INTO BUSINESS_SCALES(ID,BUSINESS_SCALE_NAME) VALUES (5,'مغازه بزرگ/کوچک');
INSERT INTO BUSINESS_SCALES(ID,BUSINESS_SCALE_NAME) VALUES (6,'ویلا/آپارتمان');
--
INSERT INTO CUSTOMER_TYPES(ID,TYPE_NAME) VALUES (1,'حقیقی');
INSERT INTO CUSTOMER_TYPES(ID,TYPE_NAME) VALUES (2,'حقوقی');
--
INSERT INTO ORGANIZATION_TYPES(ID,TYPE_NAME) VALUES (1,'سهامی عام');
INSERT INTO ORGANIZATION_TYPES(ID,TYPE_NAME) VALUES (2,'سهامی خاص');
INSERT INTO ORGANIZATION_TYPES(ID,TYPE_NAME) VALUES (3,'نهاد دولتی');
INSERT INTO ORGANIZATION_TYPES(ID,TYPE_NAME) VALUES (4,'موسسه غیر دولتی');
--
INSERT INTO OWNERSHIP_TYPES(ID,TYPE_NAME) VALUES (1,'مالک');
INSERT INTO OWNERSHIP_TYPES(ID,TYPE_NAME) VALUES (2,'مستاجر');
--
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (1,'مدیرعامل');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (2,'هیات مدیره');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (3,'معاون مالی');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (4,'معاون بازاریابی');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (5,'مدیریت');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (6,'مالک');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (7,'نماینده');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (8,'مدیرامور');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (9,'مدیرمالی');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (10,'سرپرستی');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (11,'رییس شعبه');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (12,'معاون شعبه');
--
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (1,'موبایل',0);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (2,'ثابت',0);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (3,'کار',0);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (4,'منزل',0);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (5,'فکس',0);

INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (6,'پست الکترونیک شخصی',1);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (7,'پست الکترونیک کاری',1);

INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (8,'تلگرام',2);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (9,'اینستاگرام',2);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (10,'فیسبوک',2);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (11,'توییتر',2);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (12,'واتس آپ',2);

--
INSERT INTO DOCUMENT_TYPES(ID,TYPE_NAME) VALUES (1,'doc type 1');
INSERT INTO DOCUMENT_TYPES(ID,TYPE_NAME) VALUES (2,'doc type 2');
--
INSERT INTO REQUIREMENT_STATUS_TYPES(ID,TYPE_NAME,TYPE_CODE) VALUES (1,'تعریف نیاز','rs1');
INSERT INTO REQUIREMENT_STATUS_TYPES(ID,TYPE_NAME,TYPE_CODE) VALUES (2,'در حال تصویب','rs2');
INSERT INTO REQUIREMENT_STATUS_TYPES(ID,TYPE_NAME,TYPE_CODE) VALUES (3,'امضا','rs3');
--
INSERT INTO SERVICES(ID,SERVICE_NAME,PARENT_ID) VALUES (1,'قرض الحسنه',null);
INSERT INTO SERVICES(ID, SERVICE_NAME) VALUES ('2', 'تسهیلات مضاربه');
--
INSERT INTO ORGANS (ID, ORGAN_LEVEL, ORGAN_NAME, ORGAN_ORDER) VALUES ('1', '0', 'شعب تهران', '0');
INSERT INTO ORGANS (ID, ORGAN_LEVEL, ORGAN_NAME, ORGAN_ORDER, PARENT_ID) VALUES ('2', '0', 'شعب غرب', '0', '1');
INSERT INTO ORGANS (ID, ORGAN_LEVEL, ORGAN_NAME, ORGAN_ORDER, PARENT_ID) VALUES ('3', '0', 'شعب شرق', '0', '1');
--
INSERT INTO TEAMS (ID, TEAM_NAME, REGISTER_DATE, ORGAN_ID) VALUES ('1', 'بازاریابی خارج شعبه', TO_TIMESTAMP('2019-01-23 15:19:33.401000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '2');
--
INSERT INTO PERSONNELS (ID, PERSONNEL_NAME, REGISTER_DATE, ORGAN_ID,USER_NAME) VALUES ('1', 'حمید قدیمی', TO_TIMESTAMP('2019-01-23 15:19:33.401000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '2','hamid');
INSERT INTO PERSONNELS (ID, PERSONNEL_NAME, REGISTER_DATE, ORGAN_ID,USER_NAME) VALUES ('2', 'امید مرادزاده', TO_TIMESTAMP('2019-01-23 15:19:33.401000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '2','omid');
--
INSERT INTO TEAMS_MEMBERS (ID, MEMBERSHIP_DATE,MEMBERSHIP_STATUS,TEAM_ID,PERSONNEL_ID) VALUES ('1', TO_TIMESTAMP('2019-01-23 15:20:44.393000000', 'YYYY-MM-DD HH24:MI:SS.FF'),'1', '1', '1');
--
INSERT INTO TARGETS (ID, DUE_DATE, TARGET_NAME, REGISTER_DATE, TARGET_VALUE, ORGAN_ID, SERVICE_ID, VALUE_TYPE_ID,DAYS_COUNT) VALUES ('1', TO_TIMESTAMP('2019-12-31 15:22:23.546000000', 'YYYY-MM-DD HH24:MI:SS.FF'), 'جذب سرمایه', TO_TIMESTAMP('2019-01-23 15:23:19.537000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '50000000', '2', '1', '1',186);
--
INSERT INTO TARGETS_MEMBERS (ID, TARGET_MEMBER_VALUE, DUE_DATE, REGISTER_DATE, TEAM_MEMBER_ID, TARGET_ID, VALUE_TYPE_ID) VALUES ('1', '3500000', TO_TIMESTAMP('2019-12-28 15:26:51.064000000', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2019-01-23 15:27:17.701000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '1', '1')


