INSERT INTO VALUE_TYPES(ID,TYPE_NAME) VALUES (1,'مفدار سمپل');
INSERT INTO VALUE_TYPES(ID,TYPE_NAME) VALUES (2,'dummy1');
INSERT INTO VALUE_TYPES(ID,TYPE_NAME) VALUES (3,'dummy2');
--
INSERT INTO ASSIGNED_STATUS_TYPES(ID,TYPE_NAME) VALUES (1,'status1');
INSERT INTO ASSIGNED_STATUS_TYPES(ID,TYPE_NAME) VALUES (2,'status2');
INSERT INTO ASSIGNED_STATUS_TYPES(ID,TYPE_NAME) VALUES (3,'status3');
--
INSERT INTO ATTRACTION_TYPES(ID,TYPE_NAME) VALUES (1,'type1');
INSERT INTO ATTRACTION_TYPES(ID,TYPE_NAME) VALUES (2,'type2');
INSERT INTO ATTRACTION_TYPES(ID,TYPE_NAME) VALUES (3,'type3');
--
--INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (1,'type1',1);
--INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (2,'type2',1);
--
--INSERT INTO SERVICES(ID,SERVICE_NAME,PARENT_ID) VALUES (1,'service1',null);
--INSERT INTO SERVICES(ID,SERVICE_NAME,PARENT_ID) VALUES (2,'service2',1);
--
INSERT INTO BUSINESS_SCALES(ID,BUSINESS_SCALE_NAME) VALUES (1,'bs1');
INSERT INTO BUSINESS_SCALES(ID,BUSINESS_SCALE_NAME) VALUES (2,'bs2');
--
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (1,'CEO');
INSERT INTO CONTACT_ROLES(ID,CONTACT_ROLE_NAME) VALUES (2,'CTO');
--
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (1,'MOBILE',0);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (2,'PHONE',0);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (3,'WORK_EMAIL',1);
INSERT INTO CONTACT_TYPES(ID,TYPE_NAME,TYPE_CATEGORY) VALUES (4,'INSTAGRAM',2);
--
INSERT INTO CUSTOMER_TYPES(ID,CUSTOMER_TYPE) VALUES (1,'Legal');
INSERT INTO CUSTOMER_TYPES(ID,CUSTOMER_TYPE) VALUES (2,'goverment');
--
INSERT INTO DOCUMENT_TYPES(ID,TYPE_NAME) VALUES (1,'doc type 1');
INSERT INTO DOCUMENT_TYPES(ID,TYPE_NAME) VALUES (2,'doc type 2');
--
INSERT INTO OWNERSHIP_TYPES(ID,TYPE_NAME) VALUES (1,'owner ship type1');
INSERT INTO OWNERSHIP_TYPES(ID,TYPE_NAME) VALUES (2,'owner ship type2');
--
INSERT INTO REQUIREMENT_STATUS_TYPES(ID,TYPE_NAME) VALUES (1,'rs1');
INSERT INTO REQUIREMENT_STATUS_TYPES(ID,TYPE_NAME) VALUES (2,'rs2');
--
INSERT INTO SERVICES(ID,SERVICE_NAME,PARENT_ID) VALUES (1,'service1',null);
INSERT INTO SERVICES(ID,SERVICE_NAME,PARENT_ID) VALUES (2,'service1-1',1);
INSERT INTO SERVICES(ID,SERVICE_NAME,PARENT_ID) VALUES (3,'service2',null);